const SIGN_IN = "SIGN_IN";
const SIGN_UP = "SIGN_UP";
const SET_USER_TYPE = "SET_USER_TYPE";
const UPDATE_USER = "UPDATE_USER";
const SIGNOUT = "SIGNOUT";
const CHANGE_PASSWORD = "CHANGE_PASSWORD";

export {
  SIGN_IN,
  SIGN_UP,
  SET_USER_TYPE,
  UPDATE_USER,
  SIGNOUT,
  CHANGE_PASSWORD,
};
